version: '3'

services:
  db:
    image: postgres:9.6
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/var/pg_backups
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    ports:
      - 8000
    depends_on:
      - db

volumes:
  pg_data: {}
  pg_backups: {}
