- name: Create directory structure
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ directories }}"
  tags: [consul]

- name: Download pkg
  get_url:
    url: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: /tmp/consul_{{ consul_version }}_linux_amd64.zip
  tags: [consul]

- name: Unzip binary and copy to path
  unarchive:
     src: /tmp/consul_{{ consul_version }}_linux_amd64.zip
     dest: /usr/local/bin/
     mode: 0755
     remote_src: yes

- name: Run Consul
  shell: "nohup consul agent {{ consul_extra }} \
    -ui
    -data-dir /data/consul/data \
    -config-dir /data/consul/config \
    -node={{ ansible_hostname }} \
    -bind={{ consul_ip }} \
    -client=0.0.0.0 \
    >{{ logs_dir }}/consul.log 2>&1 &"
  tags: [consul]

- name: Join clients
  shell: consul join {{ consul_server_ip }}
  when: consul_server_ip is defined
  tags: [consul]
