- name: Update /etc/hosts file
  lineinfile:
    path: /etc/hosts
    line: "{{ item.host_ip }} {{ item.host_name }}"
  with_items: "{{ hosts }}"
  tags: [common]

- name: Install zip
  apt:
    name: zip
    state: installed
    update_cache: yes
  tags: [common]

- name: Install python-pip
  apt:
    name: python-pip
    state: installed
  tags: [common]
