- name: Install Nginx
  apt:
    name: nginx
    state: installed
  tags: [nginx]

- name: Allow access through ufw to Nginx
  ufw:
    rule: allow
    name: Nginx HTTP
  tags: [nginx]

- name: Create folder for upstream Consul templates
  file:
    path: /etc/nginx/upstreams
    state: directory
  tags: [nginx]

- name: Copy upstreams
  copy:
    src: /vagrant/ansible/roles/nginx/files/maze.ctmpl
    dest: /etc/nginx/upstreams
    owner: root
    group: root
    mode: 0644
  register: copy_result
  tags: [nginx]

- name: Run Consul template on upstream
  shell: nohup consul-template -template "/etc/nginx/upstreams/maze.ctmpl:/etc/nginx/upstreams/maze.conf:/bin/bash -c 'systemctl reload nginx || true'" &
  tags: [nginx]

- name: Configure Nginx
  template:
    src: "{{ src_nginx_cfg }}"
    dest: "{{ dest_nginx_cfg }}"
  register: config_result
  tags: [nginx]

- name: Create symbolic link
  file:
    src: "{{ dest_nginx_cfg }}"
    dest: "{{ sites_enabled_nginx }}"
    state: link
  tags: [nginx]

- name: Remove default symlink
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  when: config_result|changed or copy_result|changed
  tags: [nginx]

# Configure SSL
# Check service
